const errorResponse = (description: string) => ({
  description,
  content: {
    "application/json": {
      schema: { $ref: "#/components/schemas/ErrorEnvelope" },
    },
  },
});

const authenticatedErrors = {
  "401": { $ref: "#/components/responses/Unauthorized" },
  "403": { $ref: "#/components/responses/Forbidden" },
  "429": { $ref: "#/components/responses/RateLimited" },
  "503": { $ref: "#/components/responses/Unavailable" },
};

export const headlessOpenApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "AdsBookCMS Headless API",
    version: "1.0.0",
    description: "Authenticated storefront catalog, shipping quote, checkout, order status, and tracking API.",
  },
  servers: [{ url: "/api/v1", description: "Current AdsBookCMS install" }],
  security: [{ appKeyAuth: [] }, { bearerAuth: [] }],
  tags: [
    { name: "Storefront" },
    { name: "Catalog" },
    { name: "Shipping" },
    { name: "Checkout" },
    { name: "Orders" },
    { name: "Tracking" },
    { name: "Contract" },
  ],
  paths: {
    "/storefront": {
      get: {
        operationId: "getStorefront",
        tags: ["Storefront"],
        summary: "Read storefront configuration and published content",
        "x-required-scope": "storefront:read",
        "x-api-operation": "storefrontRead",
        responses: {
          "200": {
            description: "Published storefront configuration",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/StorefrontEnvelope" },
              },
            },
          },
          "409": errorResponse("Storefront setup is incomplete"),
          "500": errorResponse("Storefront could not be loaded"),
          ...authenticatedErrors,
        },
      },
    },
    "/products": {
      get: {
        operationId: "listProducts",
        tags: ["Catalog"],
        summary: "List active products and variants",
        "x-required-scope": "catalog:read",
        "x-api-operation": "catalogList",
        parameters: [
          { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } },
          { name: "offset", in: "query", schema: { type: "integer", minimum: 0, default: 0 } },
          { name: "q", in: "query", schema: { type: "string" } },
          { name: "category", in: "query", schema: { type: "string" } },
        ],
        responses: {
          "200": {
            description: "Catalog page",
            content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogEnvelope" } } },
          },
          "500": errorResponse("Catalog could not be loaded"),
          ...authenticatedErrors,
        },
      },
    },
    "/products/{slug}": {
      get: {
        operationId: "getProduct",
        tags: ["Catalog"],
        summary: "Read one active product",
        "x-required-scope": "catalog:read",
        "x-api-operation": "catalogDetail",
        parameters: [{ name: "slug", in: "path", required: true, schema: { type: "string", minLength: 1 } }],
        responses: {
          "200": { description: "Product detail", content: { "application/json": { schema: { $ref: "#/components/schemas/ProductDetailEnvelope" } } } },
          "400": errorResponse("Product identity is missing"),
          "404": errorResponse("Product was not found"),
          "500": errorResponse("Product could not be loaded"),
          ...authenticatedErrors,
        },
      },
    },
    "/geo/districts": {
      get: {
        operationId: "searchDistricts",
        tags: ["Shipping"],
        summary: "Search supported destination districts",
        "x-required-scope": "shipping:read",
        "x-api-operation": "districtSearch",
        parameters: [
          { name: "q", in: "query", required: true, schema: { type: "string", minLength: 2 } },
          { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 30 } },
        ],
        responses: {
          "200": { description: "District matches", content: { "application/json": { schema: { $ref: "#/components/schemas/DistrictSearchEnvelope" } } } },
          "500": errorResponse("District search failed"),
          ...authenticatedErrors,
        },
      },
    },
    "/geo/shipping-rates": {
      get: {
        operationId: "quoteShippingByQuery",
        tags: ["Shipping"],
        summary: "Quote eligible shipping services using query parameters",
        "x-required-scope": "shipping:read",
        "x-api-operation": "shippingQuote",
        parameters: [
          { name: "destination_id", in: "query", required: true, schema: { type: "string", minLength: 1 } },
          { name: "variant_id", in: "query", schema: { type: "string" } },
          { name: "quantity", in: "query", schema: { type: "integer", minimum: 1, default: 1 } },
          { name: "payment_method", in: "query", schema: { type: "string", default: "cod" } },
        ],
        responses: {
          "200": { description: "Eligible rates", content: { "application/json": { schema: { $ref: "#/components/schemas/ShippingQuoteEnvelope" } } } },
          "400": errorResponse("Destination is missing"),
          "404": errorResponse("Variant was not found"),
          "500": errorResponse("Quote failed"),
          ...authenticatedErrors,
        },
      },
      post: {
        operationId: "quoteShipping",
        tags: ["Shipping"],
        summary: "Quote eligible shipping services",
        "x-required-scope": "shipping:read",
        "x-api-operation": "shippingQuote",
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/ShippingQuoteRequest" } } },
        },
        responses: {
          "200": { description: "Eligible rates", content: { "application/json": { schema: { $ref: "#/components/schemas/ShippingQuoteEnvelope" } } } },
          "400": errorResponse("Destination is missing"),
          "404": errorResponse("Variant was not found"),
          "500": errorResponse("Quote failed"),
          ...authenticatedErrors,
        },
      },
    },
    "/checkout": {
      post: {
        operationId: "createCheckout",
        tags: ["Checkout"],
        summary: "Create an order from a server-quoted shipping service",
        "x-required-scope": "checkout:write",
        "x-api-operation": "checkoutCreate",
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/CheckoutRequest" } } },
        },
        responses: {
          "201": { description: "Order created", content: { "application/json": { schema: { $ref: "#/components/schemas/CheckoutEnvelope" } } } },
          "400": errorResponse("Request JSON is invalid"),
          "409": errorResponse("Submission token was already used"),
          "422": errorResponse("Checkout input or shipping selection is invalid"),
          "500": errorResponse("Checkout failed"),
          ...authenticatedErrors,
        },
      },
    },
    "/orders/status": {
      post: {
        operationId: "getOrderStatus",
        tags: ["Orders"],
        summary: "Read order and payment status using the checkout-issued status token",
        "x-required-scope": "orders:read",
        "x-api-operation": "orderStatusRead",
        requestBody: {
          required: true,
          content: { "application/json": { schema: { $ref: "#/components/schemas/OrderStatusRequest" } } },
        },
        responses: {
          "200": { description: "Current order status", content: { "application/json": { schema: { $ref: "#/components/schemas/OrderStatusEnvelope" } } } },
          "400": errorResponse("Order identity or status token is missing"),
          "404": errorResponse("Order identity and token did not resolve"),
          "500": errorResponse("Order status could not be loaded"),
          ...authenticatedErrors,
        },
      },
    },
    "/tracking/events": {
      post: {
        operationId: "createTrackingEvent",
        tags: ["Tracking"],
        summary: "Validate and enqueue a supported tracking event",
        "x-required-scope": "tracking:write",
        "x-api-operation": "trackingCreate",
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/TrackingEventRequest" } } } },
        responses: {
          "200": { description: "Event accepted, skipped, or deduplicated", content: { "application/json": { schema: { $ref: "#/components/schemas/TrackingEventEnvelope" } } } },
          "400": errorResponse("Tracking payload is invalid"),
          "500": errorResponse("Tracking event failed"),
          ...authenticatedErrors,
        },
      },
    },
    "/openapi.json": {
      get: {
        operationId: "getOpenApiDocument",
        tags: ["Contract"],
        summary: "Read this OpenAPI document",
        "x-required-scope": "storefront:read",
        "x-api-operation": "openApiRead",
        responses: {
          "200": { description: "OpenAPI 3.1 document", content: { "application/json": { schema: { type: "object" } } } },
          ...authenticatedErrors,
        },
      },
    },
  },
  components: {
    securitySchemes: {
      appKeyAuth: { type: "apiKey", in: "header", name: "X-App-Key" },
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "API key" },
    },
    responses: {
      Unauthorized: errorResponse("API key is missing, invalid, or revoked"),
      Forbidden: errorResponse("API key scope or browser origin is not allowed"),
      RateLimited: errorResponse("Per-minute rate limit or daily quota is exhausted"),
      Unavailable: errorResponse("Required API policy or data store is unavailable"),
    },
    schemas: {
      ErrorEnvelope: {
        type: "object",
        additionalProperties: false,
        required: ["success", "timestamp", "error"],
        properties: {
          success: { const: false },
          timestamp: { type: "string", format: "date-time" },
          error: {
            type: "object",
            required: ["message", "code"],
            properties: {
              message: { type: "string" },
              code: { type: "string" },
            },
            additionalProperties: true,
          },
        },
      },
      StorefrontEnvelope: {
        type: "object",
        required: ["success", "timestamp", "storefront", "content", "tracking", "payment"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          storefront: { type: "object" },
          content: { type: "object" },
          tracking: { type: "object" },
          payment: { type: "object" },
        },
      },
      ProductVariant: {
        type: "object",
        required: ["id", "content_id", "label", "price", "compare_price"],
        properties: {
          id: { type: ["string", "integer"] },
          content_id: { type: "string" },
          label: { type: "string" },
          price: { type: "number" },
          compare_price: { type: "number" },
        },
      },
      ProductSummary: {
        type: "object",
        required: ["id", "content_id", "slug", "name", "price", "variants"],
        properties: {
          id: { type: ["string", "integer"] },
          content_id: { type: "string" },
          slug: { type: "string" },
          name: { type: "string" },
          category: { type: "string" },
          headline: { type: "string" },
          subheadline: { type: "string" },
          price: { type: "number" },
          compare_price: { type: "number" },
          image: { type: "string" },
          hero_image: { type: "string" },
          rating_value: { type: "number" },
          review_count: { type: "integer" },
          sold_count: { type: "integer" },
          variants: { type: "array", items: { $ref: "#/components/schemas/ProductVariant" } },
          urls: { type: "object" },
        },
      },
      CatalogEnvelope: {
        type: "object",
        required: ["success", "timestamp", "total", "limit", "offset", "has_more", "products"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          total: { type: "integer" },
          limit: { type: "integer" },
          offset: { type: "integer" },
          has_more: { type: "boolean" },
          products: { type: "array", items: { $ref: "#/components/schemas/ProductSummary" } },
        },
      },
      ProductDetail: {
        allOf: [
          { $ref: "#/components/schemas/ProductSummary" },
          {
            type: "object",
            required: ["description", "benefits", "key_points", "ideal_for", "offer_text", "cta_text", "reviews", "forms"],
            properties: {
              tag: { type: "string" },
              seo_title: { type: "string" },
              seo_description: { type: "string" },
              description: { type: "string" },
              benefits: { type: "array", items: { type: "string" } },
              key_points: { type: "array", items: { type: "string" } },
              ideal_for: { type: "array", items: { type: "string" } },
              offer_text: { type: "string" },
              cta_text: { type: "string" },
              reviews: {
                type: "array",
                items: {
                  type: "object",
                  required: ["name", "location", "avatar", "verified", "date", "comment", "rating"],
                  properties: {
                    name: { type: "string" },
                    location: { type: "string" },
                    avatar: { type: "string" },
                    verified: { type: "boolean" },
                    date: { type: "string" },
                    comment: { type: "string" },
                    rating: { type: "number" },
                  },
                },
              },
              forms: {
                type: "object",
                required: ["hybrid_url", "middle_url", "full_url"],
                properties: {
                  hybrid_url: { type: "string" },
                  middle_url: { type: "string" },
                  full_url: { type: "string" },
                },
              },
            },
          },
        ],
      },
      RelatedProduct: {
        type: "object",
        required: ["id", "slug", "name", "price", "compare_price", "image"],
        properties: {
          id: { type: ["string", "integer"] },
          slug: { type: "string" },
          name: { type: "string" },
          price: { type: "number" },
          compare_price: { type: "number" },
          image: { type: "string" },
        },
      },
      ProductDetailEnvelope: {
        type: "object",
        required: ["success", "timestamp", "product", "related_products"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          product: { $ref: "#/components/schemas/ProductDetail" },
          related_products: { type: "array", items: { $ref: "#/components/schemas/RelatedProduct" } },
        },
      },
      District: {
        type: "object",
        required: ["district", "city", "province", "label"],
        properties: {
          district: { type: "string" },
          city: { type: "string" },
          province: { type: "string" },
          label: { type: "string" },
        },
      },
      DistrictSearchEnvelope: {
        type: "object",
        required: ["success", "timestamp", "query", "districts"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          query: { type: "string" },
          count: { type: "integer", minimum: 0 },
          districts: { type: "array", items: { $ref: "#/components/schemas/District" } },
        },
      },
      TrackingEventRequest: {
        type: "object",
        required: ["event_name", "event_id", "event_source_url"],
        properties: {
          event_name: { type: "string", enum: ["PageView", "ViewContent", "AddToCart", "InitiateCheckout", "Purchase"] },
          event_id: { type: "string", minLength: 1, maxLength: 128 },
          event_source_url: { type: "string", format: "uri" },
          user_data: {
            type: "object",
            properties: {
              customer_phone: { type: "string" },
              customer_name: { type: "string" },
              customer_email: { type: "string", format: "email" },
              city: { type: "string" },
              province: { type: "string" },
              postal_code: { type: "string" },
              country: { type: "string" },
              external_id: { type: "string" },
              fbp: { type: "string" },
              fbc: { type: "string" },
            },
          },
          custom_data: {
            type: "object",
            properties: {
              content_name: { type: "string" },
              content_ids: { type: "array", items: { type: "string" } },
              value: { type: "number", minimum: 0 },
              currency: { const: "IDR" },
            },
          },
        },
      },
      TrackingEventEnvelope: {
        type: "object",
        required: ["success", "timestamp"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          skipped: { type: "boolean" },
          deduplicated: { type: "boolean" },
          delivered: { type: "boolean" },
          queued: { type: "boolean" },
          event_id: { type: "string" },
          event_name: { type: "string" },
          reason: { type: "string" },
        },
      },
      ShippingQuoteRequest: {
        type: "object",
        required: ["destination_id", "variant_id", "quantity", "payment_method"],
        properties: {
          destination_id: { type: "string", minLength: 1 },
          variant_id: { type: ["string", "integer"] },
          quantity: { type: "integer", minimum: 1 },
          payment_method: { type: "string", enum: ["cod", "bank_transfer", "qris", "manual_transfer"] },
          weight: { type: "number", exclusiveMinimum: 0 },
        },
      },
      ShippingRate: {
        type: "object",
        required: ["courier_code", "courier_service", "price", "cod_available", "cod_fee", "total_shipping"],
        properties: {
          courier_code: { type: "string" },
          courier_service: { type: "string" },
          price: { type: "number" },
          estimated_days: { type: ["string", "number", "null"] },
          cod_available: { type: "boolean" },
          cod_fee: { type: "number" },
          total_shipping: { type: "number" },
        },
      },
      ShippingQuoteEnvelope: {
        type: "object",
        required: ["success", "timestamp", "destination_id", "payment_method", "origin_id", "fallback_used", "rates"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          destination_id: { type: "string" },
          payment_method: { type: "string" },
          origin_id: { type: "string" },
          fallback_used: { type: "boolean" },
          rates: { type: "array", items: { $ref: "#/components/schemas/ShippingRate" } },
        },
      },
      CheckoutRequest: {
        type: "object",
        required: ["customer_name", "customer_phone", "address", "district", "province", "payment_method", "variant_id", "quantity", "submit_token", "destination_id", "courier_code"],
        properties: {
          customer_name: { type: "string", minLength: 2, maxLength: 100 },
          customer_phone: { type: "string" },
          customer_email: { type: "string", format: "email", maxLength: 160 },
          address: { type: "string", minLength: 10, maxLength: 500 },
          city: { type: "string", maxLength: 120 },
          district: { type: "string", minLength: 2, maxLength: 120 },
          province: { type: "string", minLength: 2, maxLength: 120 },
          postal_code: { type: "string", pattern: "^[0-9]{5}$" },
          payment_method: { type: "string", enum: ["cod", "bank_transfer", "qris", "manual_transfer"] },
          payment_channel: { type: "string" },
          seller_bank_account_id: { type: "integer", minimum: 1 },
          variant_id: { type: ["string", "integer"] },
          quantity: { type: "integer", minimum: 1, maximum: 100 },
          submit_token: { type: "string", minLength: 16, maxLength: 120 },
          destination_id: { type: "string", minLength: 1 },
          courier_code: { type: "string", minLength: 1 },
          courier_service: { type: "string" },
          courier_service_id: { type: "integer", minimum: 1 },
          website: { type: "string", maxLength: 0 },
        },
      },
      CheckoutOrder: {
        type: "object",
        required: ["id", "order_number", "public_status_token", "total_amount", "unit_price", "cod_service_fee", "cod_service_fee_vat", "cod_fee_bearer"],
        properties: {
          id: { type: ["integer", "string"] },
          order_number: { type: "string" },
          public_status_token: { type: "string" },
          total_amount: { type: "number" },
          unit_price: { type: "number" },
          cod_service_fee: { type: "number" },
          cod_service_fee_vat: { type: "number" },
          cod_fee_bearer: { type: "string", enum: ["buyer", "seller"] },
          seller_bank_name: { type: ["string", "null"] },
          seller_account_holder: { type: ["string", "null"] },
          seller_account_number: { type: ["string", "null"] },
        },
      },
      CheckoutEnvelope: {
        type: "object",
        required: ["success", "timestamp", "order"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          order: { $ref: "#/components/schemas/CheckoutOrder" },
        },
      },
      OrderStatusRequest: {
        type: "object",
        additionalProperties: false,
        required: ["order_number", "status_token"],
        properties: {
          order_number: { type: "string", minLength: 1 },
          status_token: { type: "string", minLength: 1 },
        },
      },
      PaymentStatus: {
        type: ["object", "null"],
        properties: {
          channel_code: { type: "string" },
          fee_bearer: { type: "string", enum: ["buyer", "seller"] },
          status: { type: "string" },
          amount: { type: "number" },
          admin_fee: { type: "number" },
          total_amount: { type: "number" },
          virtual_account: { type: ["string", "null"] },
          account_holder: { type: ["string", "null"] },
          bank_name: { type: ["string", "null"] },
          manual_transfer: { type: "boolean" },
          qr_payload: { type: ["string", "null"] },
          payment_code: { type: ["string", "null"] },
          payment_url: { type: ["string", "null"] },
          expires_at: { type: ["string", "null"] },
          error: { type: ["string", "null"] },
        },
      },
      OrderStatus: {
        type: "object",
        required: ["is_paid", "order_number", "payment_method", "payment_status", "status", "total_amount", "payment"],
        properties: {
          is_paid: { type: "boolean" },
          order_number: { type: "string" },
          payment_method: { type: "string" },
          payment_status: { type: "string" },
          status: { type: "string" },
          total_amount: { type: "number" },
          payment: { $ref: "#/components/schemas/PaymentStatus" },
        },
      },
      OrderStatusEnvelope: {
        type: "object",
        required: ["success", "timestamp", "order"],
        properties: {
          success: { const: true },
          timestamp: { type: "string", format: "date-time" },
          order: { $ref: "#/components/schemas/OrderStatus" },
        },
      },
    },
  },
} as const;
